name: First Workflow                                               
on:
  schedule:
    - cron:  '*/5 * * * *' # Every day. Ref https://crontab.guru/examples.html                                                 
jobs:                         
  get-water-depth:                            
    name: Get TDS posts                            
    runs-on: ubuntu-latest     
    steps:                             
      - name: Check-out the repo under $GITHUB_WORKSPACE                               
        uses: actions/checkout@v2         
                                                  
      - name: Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'          
                                                  
      - name: Install dependencies                              
        run: pip install pandas requests         
 
      - name: Get water depth                                
        run: python src/data/request_water_depth.py
      
#      - name: Upload artifact                      
#        uses: actions/upload-artifact@v2                        
#        with:                                 
#          name: posts                                 
#          path: posts.json

      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
          BRANCH_NAME: 'main' #optional defaults to master
